# Lesson 1: Dates and DatetimeIndex

## What This Lesson Covers

This lesson introduces the foundations of working with time-series data in Python using Pandas.

### Topics Covered

- Creating a time-series DataFrame
- Understanding date/time data types
- Converting date strings to Pandas datetime objects
- Using `pd.to_datetime()`
- Extracting information from dates using the `.dt` accessor
- Extracting:
  - Year
  - Month
  - Day
  - Day of the week
  - Day name
- Understanding the difference between a datetime column and a `DatetimeIndex`
- Creating a `DatetimeIndex` using `set_index()`
- Sorting time-series data chronologically using `sort_index()`
- Generating sequences of dates using `pd.date_range()`
- Understanding the concepts of:
  - `start`
  - `end`
  - `periods`
  - `freq`
- Understanding why chronological ordering is important in time-series analysis

## Main Functions and Attributes

```python
pd.to_datetime()
pd.date_range()

df.set_index()
df.sort_index()

df.index

df["date"].dt.year
df["date"].dt.month
df["date"].dt.day
df["date"].dt.dayofweek
df["date"].dt.day_name()

In [3]:
import numpy as np
import pandas as pd

In [4]:
data = {
    "date":
    ["2025-01-01",
        "2025-01-02",
        "2025-02-03",
        "2025-01-04",
        "2025-01-05"
    ],
    "temperature": [10, 15, 20, 25, 30]
}

In [5]:
# Change to dataframe
df = pd.DataFrame(data)
df

         date  temperature
0  2025-01-01           10
1  2025-01-02           15
2  2025-02-03           20
3  2025-01-04           25
4  2025-01-05           30

In [6]:
df.dtypes

date             str
temperature    int64
dtype: object

In [7]:
# Change to datetime
df.date = pd.to_datetime(df.date)
df.dtypes

date           datetime64[us]
temperature             int64
dtype: object

In [8]:
df.date.dt.day_name()

0    Wednesday
1     Thursday
2       Monday
3     Saturday
4       Sunday
Name: date, dtype: str

In [9]:
df.date.dt.year

0    2025
1    2025
2    2025
3    2025
4    2025
Name: date, dtype: int32

In [10]:
df.date.dt.day

0    1
1    2
2    3
3    4
4    5
Name: date, dtype: int32

In [11]:
df["month"] = df.date.dt.month # can't use df.month = df.date.dt.month , can't use attribute name to create a column
df

        date  temperature  month
0 2025-01-01           10      1
1 2025-01-02           15      1
2 2025-02-03           20      2
3 2025-01-04           25      1
4 2025-01-05           30      1

In [12]:
df = df.set_index("date")
df

            temperature  month
date
2025-01-01           10      1
2025-01-02           15      1
2025-02-03           20      2
2025-01-04           25      1
2025-01-05           30      1

In [13]:
print(df.index)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-02-03', '2025-01-04',
               '2025-01-05'],
              dtype='datetime64[us]', name='date', freq=None)

In [14]:
df.loc["2025-02-03"]

temperature    20
month           2
Name: 2025-02-03 00:00:00, dtype: int64

In [15]:
# Creating a bunch of dates
dates1 = pd.date_range("2026-05-01", "2026-05-5")
print(dates1)

DatetimeIndex(['2026-05-01', '2026-05-02', '2026-05-03', '2026-05-04',
               '2026-05-05'],
              dtype='datetime64[us]', freq='D')

In [16]:
dates2= pd.date_range("2026-05-01", periods=10)
print(dates2)

DatetimeIndex(['2026-05-01', '2026-05-02', '2026-05-03', '2026-05-04',
               '2026-05-05', '2026-05-06', '2026-05-07', '2026-05-08',
               '2026-05-09', '2026-05-10'],
              dtype='datetime64[us]', freq='D')

In [17]:
from datetime import date
# hourly
dates3 = pd.date_range(date(2026,5,1), periods=10, freq="h")
print(dates3)

DatetimeIndex(['2026-05-01 00:00:00', '2026-05-01 01:00:00',
               '2026-05-01 02:00:00', '2026-05-01 03:00:00',
               '2026-05-01 04:00:00', '2026-05-01 05:00:00',
               '2026-05-01 06:00:00', '2026-05-01 07:00:00',
               '2026-05-01 08:00:00', '2026-05-01 09:00:00'],
              dtype='datetime64[s]', freq='h')

In [18]:
# every 15 mins
dates4 = pd.date_range("2025-05-04", periods = 10, freq = "15 min")
print(dates4)

DatetimeIndex(['2025-05-04 00:00:00', '2025-05-04 00:15:00',
               '2025-05-04 00:30:00', '2025-05-04 00:45:00',
               '2025-05-04 01:00:00', '2025-05-04 01:15:00',
               '2025-05-04 01:30:00', '2025-05-04 01:45:00',
               '2025-05-04 02:00:00', '2025-05-04 02:15:00'],
              dtype='datetime64[us]', freq='15min')

In [19]:
# Sorting index
df = df.sort_index()
df

            temperature  month
date
2025-01-01           10      1
2025-01-02           15      1
2025-01-04           25      1
2025-01-05           30      1
2025-02-03           20      2

In [20]:
# print day of the week
df.index.day_name()

Index(['Wednesday', 'Thursday', 'Saturday', 'Sunday', 'Monday'], dtype='str', name='date')

In [21]:
# Print Month
df.index.month

Index([1, 1, 1, 1, 2], dtype='int32', name='date')

In [22]:
# Print Day
df.index.day

Index([1, 2, 4, 5, 3], dtype='int32', name='date')

In [23]:
# print year
df.index.year

Index([2025, 2025, 2025, 2025, 2025], dtype='int32', name='date')